version: '3.9'

services:
  app:
    container_name: app
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "yarn install"
    tty: true
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
    networks:
      - app_network

networks:
  app_network:
    name: app_network